Added more robust inter-space drone settings.
skybrush-io/studio-blender pull request #11
Opened 2024-01-16 16:49 UTC by seankovacs

**Changes**

- Adds ability to specify row & column inter-spaced drone settings instead of the fixed template layout
- Adds ability to specify the spacing for row & column of inter-spaced drones

2024-01-16 16:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/skybrush-io/studio-blender?pullRequest=11) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/skybrush-io/studio-blender?pullRequest=11) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/skybrush-io/studio-blender?pullRequest=11) it.</sub>

2024-01-17 09:58 UTC, ntamas requested changes
Thanks for the contribution, it looks good to me, but the descriptions of the newly introduced properties need to be updated (see per-line comments).

2024-01-17 09:58 UTC, ntamas commented on src/modules/sbstudio/plugin/operators/create_takeoff_grid.py
>              "Number of drones that can be placed in a single slot in the "
Description needs to be updated to reflect that this is now for a single row only.

2024-01-17 09:58 UTC, ntamas commented on src/modules/sbstudio/plugin/operators/create_takeoff_grid.py
> +            "Number of drones that can be placed in a single slot in the "
Description needs to be updated to reflect that this is now for a single column only.

2024-01-17 09:58 UTC, ntamas commented on src/modules/sbstudio/plugin/operators/create_takeoff_grid.py
> +        description="Spacing between drones in the same slot of the grid",
Description needs to be updated to reflect that this is now for a single row only.

2024-01-17 09:58 UTC, ntamas commented on src/modules/sbstudio/plugin/operators/create_takeoff_grid.py
>          description="Spacing between drones in the same slot of the grid",
Description needs to be updated to reflect that this is now for a single column only.

2024-02-16 00:21 UTC, seankovacs commented
Updated the naming and descriptions. Let me know if it makes sense

2024-02-16 18:10 UTC, ntamas approved these changes

2024-02-16 18:11 UTC, merged

2024-02-16 18:11 UTC, ntamas commented
Thank you!